[project]
name = "apis-instance-mpr"
version = "0.1.0"
description = "APIS instance MPR"
authors = [{ name = "Birger Schacht", email = "birger.schacht@oeaw.ac.at"}, { name = "Matthias Schlögl", email = "matthias.schloegl@oeaw.ac.at" } ]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apis-core-rdf==0.56.0",
    "apis-acdhch-default-settings==2.15.0",
    "psycopg",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
